apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-shift.fullname" . }}-secrets
  labels:
    {{- include "ghost-shift.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
